#!/system/bin/bash

#------------------------------------------------------------------------------------------------------
# Credit to: xpirt for sdat2img.py - dan semua yang berkontribusi 
#------------------------------------------------------------------------------------------------------
# Provided by: rendiix

me="\e[38;5;196m"
hi="\e[38;5;82m"
ku="\e[38;5;226m"
bi="\e[38;5;21m"
tbl="\e[1m"
dim="\e[2m"
no="\e[0m"
bnr() {
	echo -e ""
	echo -e "------------------------------------------------------"
	echo -e "            ${hi}${tbl}Android DAT Unpacker Tool${no}                "
	echo -e "                  ${ku}by Gunkid Dev${no}                       "
	echo -e "------------------------------------------------------"
}
brs() {
    echo -e ""
	echo -e "------------------------------------------------------"
	echo -e ""
}
info() {
echo -e "";
echo -e "${tbl}Device info:${no}";
echo -e "";
echo -e "  Model         : ${hi}$brand - $model${no}";
echo -e "  Versi Android : ${hi}$verand${no}";
echo -e "  Memori tersisa: ${hi}$mem${no}";
}
jda() {
brs;
read -s -n 1 -p "Kembali ke menu utama..."
}
csoon() {
cl;
bnr;
info;
brs;
echo -e "${hi}Fiture akan ditambahkan, dev lagi bertapa nyari materi";
echo -e "Bagi yang ingin ikut berkontribusi silahkan kontak saya di:";
echo -e " • Email   : vanzdobz@gmail.com";
echo -e " • Phone   : +62812 **** ****";
echo -e " • Discord : -${no}";
jda;
main;
}
winput() {
brs;
echo -e "${me}Masukan salah, coba lagi${no}";
jda;
main;
}
memwarn() {
cl;
bnr;
info;
brs;
echo -e "${me}Penyimpanan tidak cukup, pastikan ruang kosong lebih dari 6 GB${no}";
jda;
main;
}
miss() {
cl;
bnr;
info;
brs;
echo -e "${me}File yg dibutuhkan tidak lengkap...${no}";
echo -e "";
echo -e "${ku}Pastikan sudah memasukkan file:${no}";
echo -e "${tbl}system.new.dat${no} ${ku}dan${no} ${tbl}system.transfer.list${no}";
echo -e "${ku}kedalam folder:${no} ${tbl}$target${no}"
jda;
main;
}
udone() {
cl;
bnr;
info;
brs;
echo -e "${hi}Unpack selesai...${no}";
jda;
main;
}
quit() {
exit
}
cl() {
clear
}
unpack() {
if [ "$mem2" -lt "6800000" ]; then
memwarn;
else
unpackmain;
fi
}

unpackmain() {
if [[ -e $sdat && -e $tfrl ]]; then
    cl;
    bnr;
    info;
    brs;
    echo -e  "${ku}Sedang memproses...${no}";
    brs;
    $d2img $tfrl $sdat $target/system.img 2>/dev/null >> $logs/unpack_log.txt
    udone;
else
    miss;
fi
}

main() {
cl
bnr
info;
brs;
echo -e "${tbl}Menu:${no}";
echo -e "";
echo -e "  1. Bongkar DAT  ";
echo -e "${dim}  2. Repack DAT (comming soon)${no}";
echo -e "${dim}  3. ROM Tools (comming soon)${no}";
echo -e "  4. Keluar";
brs;
printf %s "Pilih menu kemudian tekan ENTER: ";
echo -e ""
brs;
read env;
case $env in
 1|1) unpack;;
 2|2) csoon;;
 3|3) csoon;;
 4|4) quit;;
 *) winput;;
esac
}

root=$(pwd)
build="/system/build.prop"
model="$(cat $build | grep "ro.product.model" | cut -d"=" -f 2)"
brand="$(cat $build | grep "ro.product.brand" | cut -d"=" -f 2)"
verand="$(cat $build | grep "ro.build.version.release" | cut -d"=" -f 2)"
mem="$(df -h | grep "/data" | tr -s " " | cut -d" " -f 4)"
mem2="$(df | grep "/data" | tr -s " " | cut -d" " -f 4)"
target="/sdcard/ADU_Tools"
d2img="$root/sdat2img.py"
sdat="$target/system.new.dat"
tfrl="$target/system.transfer.list"
logs="$target/logs"
envj() {
    bnr;
    echo -e "${ku}Memeriksa tools... hanya saat pertama kali menggunakan tools ini${no}"
    brs;
    chk="$(pkg list-installed python | grep "installed" | cut -d" " -f4)"
   if [ "$chk" = "" ]; then
         bnr;
         echo -e "${ku}Python tidak terinstall diperangkat anda${no}"
         brs;
         echo -e "${ku}Memasang Python...${no}"
         pkg install java
         main;
         else
         bnr;
         echo -e "${hi}Python: OK!${no}"
         brs;
         main;
   fi
}
if [ -d $target ]; then
    main;
else
    mkdir $target
    mkdir $target/logs
    envj;
    main;
fi